platform :ios, '7.0'
pod 'CDZQRScanningViewController'
pod 'Canvas', '~> 0.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'SBJson', '~> 4.0.0'
pod 'ASIHTTPRequest'
pod 'TSMessages'
pod 'InnerBand'
pod 'pop', '~> 1.0'
